# Generated by Django 4.2.2 on 2023-06-25 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpai_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='chatbot_name',
            field=models.CharField(default='NULL', max_length=100),
        ),
    ]
