# Generated by Django 4.2.2 on 2023-06-25 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpai_app', '0002_messages_chatbot_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='initial_message',
            field=models.CharField(default='NULL', max_length=100),
        ),
        migrations.AddField(
            model_name='messages',
            name='system_message',
            field=models.CharField(default='NULL', max_length=100),
        ),
    ]
