# Generated by Django 4.2.2 on 2023-06-25 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpai_app', '0003_messages_initial_message_messages_system_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='input_message',
            field=models.CharField(default='NULL', max_length=1000),
        ),
        migrations.AlterField(
            model_name='messages',
            name='output_message',
            field=models.CharField(default='NULL', max_length=1000),
        ),
    ]
